[package]
name = "plbindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
eyre = "0.6.12"
quote = "1.0.36"
syn = { version = "2.0.66", features = ["full", "extra-traits", "visit"] }
